apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  serviceName: backend-service
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shekeriev/k8s-facts
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ""
        resources:
          requests:
            storage: 2Gi
