apiVersion: v1
kind: Pod
metadata:
  name: hw-pod
spec:
  containers:
  - name: environ
    image: shekeriev/k8s-environ

    env:
      - name: HW_K8SVER
        valueFrom:
          configMapKeyRef:
            name: hwcm
            key: k8sver

      - name: HW_K8SOS
        valueFrom:
          configMapKeyRef:
            name: hwcm
            key: k8sos

      - name: HW_PORT
        valueFrom:
          configMapKeyRef:
            name: hwcm
            key: port.conf

    volumeMounts:
      - name: config-vol
        mountPath: /config
      - name: secret-vol
        mountPath: /secret
        readOnly: true

  volumes:
    - name: config-vol
      configMap:
        name: hwcm
        items:
          - key: main.conf
            path: main.conf

    - name: secret-vol
      secret:
        secretName: hwsec
